version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./volumes/rabbitmq:/var/lib/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./volumes/mongo:/data/db

  order-service:
    build:
      context: .
      dockerfile: services/order-service/Dockerfile
    container_name: order-service
    ports:
      - "3001:3000"
    depends_on:
      - rabbitmq
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/order_db
      - RABBITMQ_URI=amqp://user:password@rabbitmq:5672
      - PORT=3000
    volumes:
      - ./packages/event-types:/usr/src/packages/event-types

  inventory-service:
    build:
      context: .
      dockerfile: services/inventory-service/Dockerfile
    container_name: inventory-service
    ports:
      - "3002:3000"
    depends_on:
      - rabbitmq
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/inventory_db
      - RABBITMQ_URI=amqp://user:password@rabbitmq:5672
      - PORT=3000
    volumes:
      - ./services/inventory-service/src:/usr/src/app/src
      - ./packages/event-types:/usr/src/packages/event-types

  notification-service:
    build:
      context: .
      dockerfile: services/notification-service/Dockerfile
    container_name: notification-service
    ports:
      - "3003:3000"
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URI=amqp://user:password@rabbitmq:5672
      - PORT=3000
    volumes:
      - ./services/notification-service/src:/usr/src/app/src
      - ./packages/event-types:/usr/src/packages/event-types

volumes:
  mongodb_data:
  rabbitmq_data:
